[pytest]
filterwarnings =
    error:Using the initialization functions in flask_caching\.backend is deprecated\..*:DeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal.*:DeprecationWarning
    ignore:The default datetime adapter is deprecated as of Python 3\.12.*:DeprecationWarning
    ignore:ast\.NameConstant is deprecated and will be removed in Python 3\.14.*:DeprecationWarning
    ignore:transform is deprecated, use set_matrix instead\.:DeprecationWarning
    ignore:text_matrix is deprecated, use set_text_matrix instead\.:DeprecationWarning
    error::sqlalchemy.exc.LegacyAPIWarning
