"""add_indexes_and_sync

Revision ID: 11237fb81943
Revises: 121683435140
Create Date: 2026-01-01 16:19:28.038244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11237fb81943'
down_revision = '121683435140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index('gin_checks_check_number_trgm', postgresql_ops={'check_number': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('idx_checks_customer_date')
        batch_op.drop_index('idx_checks_payment')
        batch_op.drop_index('idx_checks_status')
        batch_op.drop_index('ix_checks_check_date')
        batch_op.drop_index('ix_checks_check_date_status')
        batch_op.drop_index('ix_checks_customer_id_date')
        batch_op.drop_index('ix_checks_date_pending', postgresql_where="((status)::text = 'PENDING'::text)")
        batch_op.drop_index('ix_checks_is_archived_status')
        batch_op.drop_index('ix_checks_partner_id_date')
        batch_op.drop_index('ix_checks_payment_id_status')
        batch_op.drop_index('ix_checks_status_due_date_direction')
        batch_op.drop_index('ix_checks_supplier_id_date')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('gin_customers_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_customers_category')
        batch_op.drop_index('ix_customers_is_active')
        batch_op.drop_index('ix_customers_is_archived')
        batch_op.drop_index('ix_customers_is_online')
        batch_op.drop_index('ix_customers_lower_email')
        batch_op.drop_index('ix_customers_name')
        batch_op.drop_index('ix_customers_phone')
        batch_op.create_index('ix_customers_active_name', ['is_active', 'name'], unique=False)
        batch_op.create_index('ix_customers_checks_in_balance', ['checks_in_balance'], unique=False)
        batch_op.create_index('ix_customers_checks_out_balance', ['checks_out_balance'], unique=False)
        batch_op.create_index('ix_customers_credit_limit', ['credit_limit'], unique=False)
        batch_op.create_index('ix_customers_expenses_balance', ['expenses_balance'], unique=False)
        batch_op.create_index('ix_customers_invoices_balance', ['invoices_balance'], unique=False)
        batch_op.create_index('ix_customers_online_active', ['is_online', 'is_active'], unique=False)
        batch_op.create_index('ix_customers_online_orders_balance', ['online_orders_balance'], unique=False)
        batch_op.create_index('ix_customers_opening_balance', ['opening_balance'], unique=False)
        batch_op.create_index('ix_customers_payments_in_balance', ['payments_in_balance'], unique=False)
        batch_op.create_index('ix_customers_payments_out_balance', ['payments_out_balance'], unique=False)
        batch_op.create_index('ix_customers_preorders_balance', ['preorders_balance'], unique=False)
        batch_op.create_index('ix_customers_returned_checks_in_balance', ['returned_checks_in_balance'], unique=False)
        batch_op.create_index('ix_customers_returned_checks_out_balance', ['returned_checks_out_balance'], unique=False)
        batch_op.create_index('ix_customers_returns_balance', ['returns_balance'], unique=False)
        batch_op.create_index('ix_customers_sales_balance', ['sales_balance'], unique=False)
        batch_op.create_index('ix_customers_service_expenses_balance', ['service_expenses_balance'], unique=False)
        batch_op.create_index('ix_customers_services_balance', ['services_balance'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('idx_expenses_customer_date')
        batch_op.drop_index('idx_expenses_date')
        batch_op.drop_index('idx_expenses_partner_date')
        batch_op.drop_index('idx_expenses_type')
        batch_op.drop_index('idx_expenses_warehouse_date')
        batch_op.create_index('ix_expense_amount', ['amount'], unique=False)

    with op.batch_alter_table('gl_batches', schema=None) as batch_op:
        batch_op.create_index('ix_gl_posted_status', ['status', 'posted_at'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('idx_invoices_customer_date')
        batch_op.drop_index('ix_invoices_customer_date')
        batch_op.create_index('ix_inv_cust_cancelled', ['customer_id', 'cancelled_at'], unique=False)
        batch_op.create_index('ix_inv_customer_date', ['customer_id', 'invoice_date'], unique=False)
        batch_op.create_index('ix_inv_kind_date', ['kind', 'invoice_date'], unique=False)
        batch_op.create_index('ix_inv_total_amount', ['total_amount'], unique=False)

    with op.batch_alter_table('partner_settlement_lines', schema=None) as batch_op:
        batch_op.create_index('ix_partner_settle_line_product', ['product_id'], unique=False)
        batch_op.create_index('ix_partner_settle_line_warehouse', ['warehouse_id'], unique=False)

    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.create_index('ix_partner_settle_closing_balance', ['closing_balance'], unique=False)
        batch_op.create_index('ix_partner_settle_opening_balance', ['opening_balance'], unique=False)
        batch_op.create_index('ix_partner_settle_total_due', ['total_due'], unique=False)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('gin_partners_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_partners_currency_balance')
        batch_op.drop_index('ix_partners_is_archived_balance')
        batch_op.drop_index('ix_partners_name_phone')
        batch_op.drop_index('ix_partners_share_percentage')
        batch_op.create_index('ix_partners_opening_balance', ['opening_balance'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('gin_payments_notes_trgm', postgresql_ops={'notes': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('gin_payments_reference_trgm', postgresql_ops={'reference': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('idx_payments_customer_date')
        batch_op.drop_index('idx_payments_status')
        batch_op.drop_index('ix_payments_currency')
        batch_op.drop_index('ix_payments_customer_date')
        batch_op.drop_index('ix_payments_customer_date_completed', postgresql_where="((is_archived = false) AND ((status)::text = 'COMPLETED'::text))")
        batch_op.drop_index('ix_payments_date')
        batch_op.drop_index('ix_payments_date_active', postgresql_where='(is_archived = false)')
        batch_op.drop_index('ix_payments_direction')
        batch_op.drop_index('ix_payments_partner_date')
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index('ix_payments_supplier_date')
        batch_op.create_index('ix_pay_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_pay_cust_stat_dir', ['customer_id', 'status', 'direction'], unique=False)
        batch_op.create_index('ix_pay_exp_stat_dir', ['expense_id', 'status', 'direction'], unique=False)
        batch_op.create_index('ix_pay_method_date', ['method', 'payment_date'], unique=False)
        batch_op.create_index('ix_pay_shp_stat_dir', ['shipment_id', 'status', 'direction'], unique=False)
        batch_op.create_index('ix_pay_srv_stat_dir', ['service_id', 'status', 'direction'], unique=False)
        batch_op.create_index('ix_pay_total_amount', ['total_amount'], unique=False)

    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.create_index('ix_preorders_date_status', ['preorder_date', 'status'], unique=False)
        batch_op.create_index('ix_preorders_pay_method', ['payment_method'], unique=False)
        batch_op.create_index('ix_preorders_prepaid', ['prepaid_amount'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_is_published', ['is_published'], unique=False)
        batch_op.create_index('ix_products_supplier', ['supplier_id'], unique=False)
        batch_op.create_index('ix_products_vehicle_type', ['vehicle_type_id'], unique=False)
        batch_op.create_index('ix_products_warehouse', ['warehouse_id'], unique=False)

    with op.batch_alter_table('project_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_score')
        batch_op.create_index('ix_risk_score', ['risk_score'], unique=False, postgresql_ops={'risk_score': 'DESC'})

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_index('idx_sale_returns_customer')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('idx_sales_customer_date')
        batch_op.drop_index('ix_sales_customer_date')
        batch_op.drop_index('ix_sales_date')
        batch_op.create_index('ix_sales_archived', ['is_archived', 'archived_at'], unique=False)
        batch_op.create_index('ix_sales_balance_due', ['balance_due'], unique=False)
        batch_op.create_index('ix_sales_seller_date', ['seller_id', 'sale_date'], unique=False)
        batch_op.create_index('ix_sales_total_amount', ['total_amount'], unique=False)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_services_customer_date')
        batch_op.drop_index('ix_service_received_active', postgresql_where="((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'DIAGNOSIS'::character varying])::text[]))")
        batch_op.drop_index('ix_service_requests_customer_date')
        batch_op.drop_index('ix_service_requests_customer_status_date')
        batch_op.drop_index('ix_service_requests_mechanic_status')
        batch_op.drop_index('ix_service_requests_received_status')
        batch_op.drop_index('ix_service_requests_status_created_at')
        batch_op.drop_index('ix_service_requests_status_priority')
        batch_op.create_index('ix_srv_chassis', ['chassis_number'], unique=False)
        batch_op.create_index('ix_srv_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('ix_srv_cost_center', ['cost_center_id'], unique=False)
        batch_op.create_index('ix_srv_created_status', ['created_at', 'status'], unique=False)
        batch_op.create_index('ix_srv_cust_status', ['customer_id', 'status'], unique=False)
        batch_op.create_index('ix_srv_expected_delivery', ['expected_delivery'], unique=False)
        batch_op.create_index('ix_srv_mech_status', ['mechanic_id', 'status'], unique=False)
        batch_op.create_index('ix_srv_total_amount', ['total_amount'], unique=False)
        batch_op.create_index('ix_srv_vehicle_model', ['vehicle_model'], unique=False)
        batch_op.create_index('ix_srv_vehicle_vrn', ['vehicle_vrn'], unique=False)

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_levels_prod')
        batch_op.drop_index('ix_stock_levels_wh')
        batch_op.drop_index('ix_stock_levels_wh_prod')
        batch_op.create_index('ix_stock_quantity', ['quantity'], unique=False)

    with op.batch_alter_table('supplier_settlement_lines', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_settle_line_product', ['product_id'], unique=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('gin_suppliers_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_suppliers_currency')
        batch_op.drop_index('ix_suppliers_lower_email')
        batch_op.drop_index('ix_suppliers_name')
        batch_op.create_index('ix_supp_contact', ['contact'], unique=False)
        batch_op.create_index('ix_supp_name_active', ['name', 'is_archived'], unique=False)
        batch_op.create_index('ix_supp_opening_balance', ['opening_balance'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_last_login')
        batch_op.drop_index('ix_users_last_seen')
        batch_op.drop_index('ix_users_lower_email')
        batch_op.drop_index('ix_users_lower_username')

    with op.batch_alter_table('warehouse_partner_shares', schema=None) as batch_op:
        batch_op.create_index('ix_wps_share_percentage', ['share_percentage'], unique=False)

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index('ix_warehouses_parent', ['parent_id'], unique=False)
        batch_op.create_index('ix_warehouses_partner', ['partner_id'], unique=False)
        batch_op.create_index('ix_warehouses_share_percent', ['share_percent'], unique=False)
        batch_op.create_index('ix_warehouses_supplier', ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('ix_warehouses_supplier')
        batch_op.drop_index('ix_warehouses_share_percent')
        batch_op.drop_index('ix_warehouses_partner')
        batch_op.drop_index('ix_warehouses_parent')

    with op.batch_alter_table('warehouse_partner_shares', schema=None) as batch_op:
        batch_op.drop_index('ix_wps_share_percentage')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_lower_username', [sa.text('lower(username::text)')], unique=False)
        batch_op.create_index('ix_users_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_users_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('ix_users_last_login', ['last_login'], unique=False)
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('ix_supp_opening_balance')
        batch_op.drop_index('ix_supp_name_active')
        batch_op.drop_index('ix_supp_contact')
        batch_op.create_index('ix_suppliers_name', ['name'], unique=False)
        batch_op.create_index('ix_suppliers_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_suppliers_currency', ['currency'], unique=False)
        batch_op.create_index('gin_suppliers_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('supplier_settlement_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_settle_line_product')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_quantity')
        batch_op.create_index('ix_stock_levels_wh_prod', ['warehouse_id', 'product_id'], unique=False)
        batch_op.create_index('ix_stock_levels_wh', ['warehouse_id'], unique=False)
        batch_op.create_index('ix_stock_levels_prod', ['product_id'], unique=False)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_srv_vehicle_vrn')
        batch_op.drop_index('ix_srv_vehicle_model')
        batch_op.drop_index('ix_srv_total_amount')
        batch_op.drop_index('ix_srv_mech_status')
        batch_op.drop_index('ix_srv_expected_delivery')
        batch_op.drop_index('ix_srv_cust_status')
        batch_op.drop_index('ix_srv_created_status')
        batch_op.drop_index('ix_srv_cost_center')
        batch_op.drop_index('ix_srv_completed_at')
        batch_op.drop_index('ix_srv_chassis')
        batch_op.create_index('ix_service_requests_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('ix_service_requests_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_service_requests_received_status', ['received_at', 'status'], unique=False)
        batch_op.create_index('ix_service_requests_mechanic_status', ['mechanic_id', 'status'], unique=False)
        batch_op.create_index('ix_service_requests_customer_status_date', ['customer_id', 'status', 'received_at'], unique=False)
        batch_op.create_index('ix_service_requests_customer_date', ['customer_id', 'received_at'], unique=False)
        batch_op.create_index('ix_service_received_active', ['received_at'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'DIAGNOSIS'::character varying])::text[]))")
        batch_op.create_index('idx_services_customer_date', ['customer_id', 'completed_at'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_total_amount')
        batch_op.drop_index('ix_sales_seller_date')
        batch_op.drop_index('ix_sales_balance_due')
        batch_op.drop_index('ix_sales_archived')
        batch_op.create_index('ix_sales_date', ['sale_date'], unique=False)
        batch_op.create_index('ix_sales_customer_date', ['customer_id', 'sale_date'], unique=False)
        batch_op.create_index('idx_sales_customer_date', ['customer_id', 'sale_date'], unique=False)

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.create_index('idx_sale_returns_customer', ['customer_id'], unique=False)

    with op.batch_alter_table('project_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_score', postgresql_ops={'risk_score': 'DESC'})
        batch_op.create_index('ix_risk_score', [sa.text('risk_score DESC')], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_warehouse')
        batch_op.drop_index('ix_products_vehicle_type')
        batch_op.drop_index('ix_products_supplier')
        batch_op.drop_index('ix_products_is_published')

    with op.batch_alter_table('preorders', schema=None) as batch_op:
        batch_op.drop_index('ix_preorders_prepaid')
        batch_op.drop_index('ix_preorders_pay_method')
        batch_op.drop_index('ix_preorders_date_status')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_pay_total_amount')
        batch_op.drop_index('ix_pay_srv_stat_dir')
        batch_op.drop_index('ix_pay_shp_stat_dir')
        batch_op.drop_index('ix_pay_method_date')
        batch_op.drop_index('ix_pay_exp_stat_dir')
        batch_op.drop_index('ix_pay_cust_stat_dir')
        batch_op.drop_index('ix_pay_created_by')
        batch_op.create_index('ix_payments_supplier_date', ['supplier_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index('ix_payments_partner_date', ['partner_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_direction', ['direction'], unique=False)
        batch_op.create_index('ix_payments_date_active', ['payment_date'], unique=False, postgresql_where='(is_archived = false)')
        batch_op.create_index('ix_payments_date', ['payment_date'], unique=False)
        batch_op.create_index('ix_payments_customer_date_completed', ['customer_id', 'payment_date'], unique=False, postgresql_where="((is_archived = false) AND ((status)::text = 'COMPLETED'::text))")
        batch_op.create_index('ix_payments_customer_date', ['customer_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_currency', ['currency'], unique=False)
        batch_op.create_index('idx_payments_status', ['status'], unique=False)
        batch_op.create_index('idx_payments_customer_date', ['customer_id', 'payment_date'], unique=False)
        batch_op.create_index('gin_payments_reference_trgm', ['reference'], unique=False, postgresql_ops={'reference': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('gin_payments_notes_trgm', ['notes'], unique=False, postgresql_ops={'notes': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('ix_partners_opening_balance')
        batch_op.create_index('ix_partners_share_percentage', ['share_percentage'], unique=False)
        batch_op.create_index('ix_partners_name_phone', ['name', 'phone_number'], unique=False)
        batch_op.create_index('ix_partners_is_archived_balance', ['is_archived', 'current_balance'], unique=False)
        batch_op.create_index('ix_partners_currency_balance', ['currency', 'current_balance'], unique=False)
        batch_op.create_index('gin_partners_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_settle_total_due')
        batch_op.drop_index('ix_partner_settle_opening_balance')
        batch_op.drop_index('ix_partner_settle_closing_balance')

    with op.batch_alter_table('partner_settlement_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_settle_line_warehouse')
        batch_op.drop_index('ix_partner_settle_line_product')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_total_amount')
        batch_op.drop_index('ix_inv_kind_date')
        batch_op.drop_index('ix_inv_customer_date')
        batch_op.drop_index('ix_inv_cust_cancelled')
        batch_op.create_index('ix_invoices_customer_date', ['customer_id', 'invoice_date'], unique=False)
        batch_op.create_index('idx_invoices_customer_date', ['customer_id', 'invoice_date'], unique=False)

    with op.batch_alter_table('gl_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_gl_posted_status')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_amount')
        batch_op.create_index('idx_expenses_warehouse_date', ['warehouse_id', 'date'], unique=False)
        batch_op.create_index('idx_expenses_type', ['type_id'], unique=False)
        batch_op.create_index('idx_expenses_partner_date', ['partner_id', 'date'], unique=False)
        batch_op.create_index('idx_expenses_date', ['date'], unique=False)
        batch_op.create_index('idx_expenses_customer_date', ['customer_id', 'date'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_services_balance')
        batch_op.drop_index('ix_customers_service_expenses_balance')
        batch_op.drop_index('ix_customers_sales_balance')
        batch_op.drop_index('ix_customers_returns_balance')
        batch_op.drop_index('ix_customers_returned_checks_out_balance')
        batch_op.drop_index('ix_customers_returned_checks_in_balance')
        batch_op.drop_index('ix_customers_preorders_balance')
        batch_op.drop_index('ix_customers_payments_out_balance')
        batch_op.drop_index('ix_customers_payments_in_balance')
        batch_op.drop_index('ix_customers_opening_balance')
        batch_op.drop_index('ix_customers_online_orders_balance')
        batch_op.drop_index('ix_customers_online_active')
        batch_op.drop_index('ix_customers_invoices_balance')
        batch_op.drop_index('ix_customers_expenses_balance')
        batch_op.drop_index('ix_customers_credit_limit')
        batch_op.drop_index('ix_customers_checks_out_balance')
        batch_op.drop_index('ix_customers_checks_in_balance')
        batch_op.drop_index('ix_customers_active_name')
        batch_op.create_index('ix_customers_phone', ['phone'], unique=False)
        batch_op.create_index('ix_customers_name', ['name'], unique=False)
        batch_op.create_index('ix_customers_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_customers_is_online', ['is_online'], unique=False)
        batch_op.create_index('ix_customers_is_archived', ['is_archived'], unique=False)
        batch_op.create_index('ix_customers_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_customers_category', ['category'], unique=False)
        batch_op.create_index('gin_customers_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index('ix_checks_supplier_id_date', ['supplier_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_status_due_date_direction', ['status', 'check_due_date', 'direction'], unique=False)
        batch_op.create_index('ix_checks_payment_id_status', ['payment_id', 'status'], unique=False)
        batch_op.create_index('ix_checks_partner_id_date', ['partner_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_is_archived_status', ['is_archived', 'status'], unique=False)
        batch_op.create_index('ix_checks_date_pending', ['check_date'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
        batch_op.create_index('ix_checks_customer_id_date', ['customer_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_check_date_status', ['check_date', 'status'], unique=False)
        batch_op.create_index('ix_checks_check_date', ['check_date'], unique=False)
        batch_op.create_index('idx_checks_status', ['status'], unique=False)
        batch_op.create_index('idx_checks_payment', ['payment_id'], unique=False)
        batch_op.create_index('idx_checks_customer_date', ['customer_id', 'check_date'], unique=False)
        batch_op.create_index('gin_checks_check_number_trgm', ['check_number'], unique=False, postgresql_ops={'check_number': 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###
