"""add return_date to sale_return

Revision ID: 94948c531c03
Revises: 10f6c0ee04dc
Create Date: 2026-03-01 00:25:26.318693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94948c531c03'
down_revision = '10f6c0ee04dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_index('gin_checks_check_number_trgm', postgresql_ops={'check_number': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_checks_check_date')
        batch_op.drop_index('ix_checks_check_date_status')
        batch_op.drop_index('ix_checks_customer_id_date')
        batch_op.drop_index('ix_checks_date_pending', postgresql_where="((status)::text = 'PENDING'::text)")
        batch_op.drop_index('ix_checks_is_archived_status')
        batch_op.drop_index('ix_checks_partner_id_date')
        batch_op.drop_index('ix_checks_payment_id_status')
        batch_op.drop_index('ix_checks_status_due_date_direction')
        batch_op.drop_index('ix_checks_supplier_id_date')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('gin_customers_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_customers_category')
        batch_op.drop_index('ix_customers_is_active')
        batch_op.drop_index('ix_customers_is_archived')
        batch_op.drop_index('ix_customers_is_online')
        batch_op.drop_index('ix_customers_lower_email')
        batch_op.drop_index('ix_customers_name')
        batch_op.drop_index('ix_customers_phone')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_customer_date')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('gin_partners_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_partners_currency_balance')
        batch_op.drop_index('ix_partners_is_archived_balance')
        batch_op.drop_index('ix_partners_name_phone')
        batch_op.drop_index('ix_partners_share_percentage')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('gin_payments_notes_trgm', postgresql_ops={'notes': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('gin_payments_reference_trgm', postgresql_ops={'reference': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_payments_currency')
        batch_op.drop_index('ix_payments_customer_date')
        batch_op.drop_index('ix_payments_customer_date_completed', postgresql_where="((is_archived = false) AND ((status)::text = 'COMPLETED'::text))")
        batch_op.drop_index('ix_payments_date')
        batch_op.drop_index('ix_payments_date_active', postgresql_where='(is_archived = false)')
        batch_op.drop_index('ix_payments_direction')
        batch_op.drop_index('ix_payments_partner_date')
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index('ix_payments_supplier_date')

    with op.batch_alter_table('project_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_score')
        batch_op.create_index('ix_risk_score', ['risk_score'], unique=False, postgresql_ops={'risk_score': 'DESC'})

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sale_returns_return_date'), ['return_date'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_customer_date')
        batch_op.drop_index('ix_sales_date')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_service_received_active', postgresql_where="((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'DIAGNOSIS'::character varying])::text[]))")
        batch_op.drop_index('ix_service_requests_customer_date')
        batch_op.drop_index('ix_service_requests_customer_status_date')
        batch_op.drop_index('ix_service_requests_mechanic_status')
        batch_op.drop_index('ix_service_requests_received_status')
        batch_op.drop_index('ix_service_requests_status_created_at')
        batch_op.drop_index('ix_service_requests_status_priority')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_levels_prod')
        batch_op.drop_index('ix_stock_levels_wh')
        batch_op.drop_index('ix_stock_levels_wh_prod')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('gin_suppliers_name_trgm', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index('ix_suppliers_currency')
        batch_op.drop_index('ix_suppliers_lower_email')
        batch_op.drop_index('ix_suppliers_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_last_login')
        batch_op.drop_index('ix_users_last_seen')
        batch_op.drop_index('ix_users_lower_email')
        batch_op.drop_index('ix_users_lower_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_lower_username', [sa.text('lower(username::text)')], unique=False)
        batch_op.create_index('ix_users_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_users_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('ix_users_last_login', ['last_login'], unique=False)
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_name', ['name'], unique=False)
        batch_op.create_index('ix_suppliers_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_suppliers_currency', ['currency'], unique=False)
        batch_op.create_index('gin_suppliers_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.create_index('ix_stock_levels_wh_prod', ['warehouse_id', 'product_id'], unique=False)
        batch_op.create_index('ix_stock_levels_wh', ['warehouse_id'], unique=False)
        batch_op.create_index('ix_stock_levels_prod', ['product_id'], unique=False)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index('ix_service_requests_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('ix_service_requests_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_service_requests_received_status', ['received_at', 'status'], unique=False)
        batch_op.create_index('ix_service_requests_mechanic_status', ['mechanic_id', 'status'], unique=False)
        batch_op.create_index('ix_service_requests_customer_status_date', ['customer_id', 'status', 'received_at'], unique=False)
        batch_op.create_index('ix_service_requests_customer_date', ['customer_id', 'received_at'], unique=False)
        batch_op.create_index('ix_service_received_active', ['received_at'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'DIAGNOSIS'::character varying])::text[]))")

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('ix_sales_date', ['sale_date'], unique=False)
        batch_op.create_index('ix_sales_customer_date', ['customer_id', 'sale_date'], unique=False)

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_returns_return_date'))
        batch_op.drop_column('return_date')

    with op.batch_alter_table('project_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_score', postgresql_ops={'risk_score': 'DESC'})
        batch_op.create_index('ix_risk_score', [sa.text('risk_score DESC')], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_supplier_date', ['supplier_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index('ix_payments_partner_date', ['partner_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_direction', ['direction'], unique=False)
        batch_op.create_index('ix_payments_date_active', ['payment_date'], unique=False, postgresql_where='(is_archived = false)')
        batch_op.create_index('ix_payments_date', ['payment_date'], unique=False)
        batch_op.create_index('ix_payments_customer_date_completed', ['customer_id', 'payment_date'], unique=False, postgresql_where="((is_archived = false) AND ((status)::text = 'COMPLETED'::text))")
        batch_op.create_index('ix_payments_customer_date', ['customer_id', 'payment_date'], unique=False)
        batch_op.create_index('ix_payments_currency', ['currency'], unique=False)
        batch_op.create_index('gin_payments_reference_trgm', ['reference'], unique=False, postgresql_ops={'reference': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('gin_payments_notes_trgm', ['notes'], unique=False, postgresql_ops={'notes': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index('ix_partners_share_percentage', ['share_percentage'], unique=False)
        batch_op.create_index('ix_partners_name_phone', ['name', 'phone_number'], unique=False)
        batch_op.create_index('ix_partners_is_archived_balance', ['is_archived', 'current_balance'], unique=False)
        batch_op.create_index('ix_partners_currency_balance', ['currency', 'current_balance'], unique=False)
        batch_op.create_index('gin_partners_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_customer_date', ['customer_id', 'invoice_date'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_phone', ['phone'], unique=False)
        batch_op.create_index('ix_customers_name', ['name'], unique=False)
        batch_op.create_index('ix_customers_lower_email', [sa.text('lower(email::text)')], unique=False)
        batch_op.create_index('ix_customers_is_online', ['is_online'], unique=False)
        batch_op.create_index('ix_customers_is_archived', ['is_archived'], unique=False)
        batch_op.create_index('ix_customers_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_customers_category', ['category'], unique=False)
        batch_op.create_index('gin_customers_name_trgm', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_index('ix_checks_supplier_id_date', ['supplier_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_status_due_date_direction', ['status', 'check_due_date', 'direction'], unique=False)
        batch_op.create_index('ix_checks_payment_id_status', ['payment_id', 'status'], unique=False)
        batch_op.create_index('ix_checks_partner_id_date', ['partner_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_is_archived_status', ['is_archived', 'status'], unique=False)
        batch_op.create_index('ix_checks_date_pending', ['check_date'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
        batch_op.create_index('ix_checks_customer_id_date', ['customer_id', 'check_date'], unique=False)
        batch_op.create_index('ix_checks_check_date_status', ['check_date', 'status'], unique=False)
        batch_op.create_index('ix_checks_check_date', ['check_date'], unique=False)
        batch_op.create_index('gin_checks_check_number_trgm', ['check_number'], unique=False, postgresql_ops={'check_number': 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###
